application:
  actions: actions
  runtimeManifest:
    packages:
      franklin:
        license: Apache-2.0
        actions:
          ssr:
            function: ssr/dist/main.js
            web: 'yes'
            runtime: 'nodejs:16'
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
              final: true
          list:
            function: list/index.js
            web: 'yes'
            runtime: 'nodejs:16'
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
              final: true
      litmus:
        license: Apache-2.0
        actions:
          preview:
            function: preview/index.js
            web: 'yes'
            runtime: 'nodejs:14'
            inputs:
              LOG_LEVEL: debug
              LITMUS_TOKEN: $LITMUS_TOKEN
            annotations:
              require-adobe-auth: false
              final: true